databases:
  - name: assessmentamt
    databaseName: assessmentamt
    user: assessmentamt
    plan: free

services:
  - type: web
    name: assessmentamt
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: assessmentamt
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction